vich_uploader:
    db_driver: orm

    mappings:
        blogs_images:
            uri_prefix: /images/blogs
            upload_destination: '%kernel.project_dir%/public/images/blogs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

